name: Build and test

on:
  workflow_call:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Get UV version
        shell: bash
        run: |
          UV_VERSION=$(jq -r '.packages[] | select(startswith("uv@")) | split("@")[1]' devbox.json)
          echo "UV_VERSION=$UV_VERSION" >> $GITHUB_ENV

      - name: Setup Python UV
        uses: astral-sh/setup-uv@v7
        with:
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        shell: bash
        run: uv sync

      - name: Generate .env from .env.example
        shell: bash
        # env: Add variables for .env
        run: |
          > .env

          while IFS= read -r line || [[ -n "$line" ]]; do
            if [[ -z "$line" || "$line" =~ ^# ]]; then
              echo "$line" >> .env
              continue
            fi

            KEY="${line%%=*}"
            VALUE="${line#*=}"

            if [[ "$VALUE" =~ \<YOUR_.*\> ]]; then
              SECRET="${!KEY}"
              if [ -z "$SECRET" ]; then
                echo "Warning: environment variable '$KEY' is not set!"
                SECRET=""
              fi
              echo "$KEY=$SECRET" >> .env
            else
              echo "$line" >> .env
            fi
          done < .env.example

      - name: Lint server
        shell: bash
        run: uvx ruff check src/

      - name: Check test files
        id: check_tests
        shell: bash
        run: |
          if ls tests 2>/dev/null | grep -q '^test_.*\.py$'; then
            echo "run_tests=true" >> $GITHUB_OUTPUT
          else
            echo "run_tests=false" >> $GITHUB_OUTPUT
          fi

      - name: Test server
        if: steps.check_tests.outputs.run_tests == 'true'
        shell: bash
        run: PY_ENV=test uv run pytest tests

